{{- if or .Values.secrets.jwtSecret .Values.secrets.adminKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keepassex-server.fullname" . }}
  labels:
    {{- include "keepassex-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  {{- else }}
  jwt-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.adminKey }}
  admin-key: {{ .Values.secrets.adminKey | b64enc | quote }}
  {{- else }}
  admin-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
